tasks:
  - init: "clear && echo Installing Tabris, please stand by... && npm install tabris-cli -g"
    command: "npm install && clear && npm run gitpod"
ports:
  - port: 8080
    onOpen: open-preview
